{
  "vid": "077bbadf-f2f4-11e6-92a7-902b34361349",
  "topic": "diffoscope -- arbitrary file write",
  "affects": [
    {
      "name": [
        "py34-diffoscope",
        "py35-diffoscope",
        "py36-diffoscope"
      ],
      "range": [
        {
          "lt": "76",
          "ge": "67"
        }
      ]
    }
  ],
  "description": {
    "xmlns": "http://www.w3.org/1999/xhtml",
    "text": "\n\t<p>Ximin Luo reports:</p>\n\t<blockquote cite=\"https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854723\">\n\t  <p>[v67] introduced a security hole where diffoscope may write to\n\t    arbitrary locations on disk depending on the contents of an\n\t    untrusted archive.</p>\n\t</blockquote>\n      "
  },
  "references": {
    "url": [
      "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854723"
    ],
    "cvename": [
      "CVE-2017-0359"
    ]
  },
  "dates": {
    "discovery": "2017-02-09",
    "entry": "2017-02-14",
    "modified": "2017-02-16"
  }
}
