{
  "vid": "28a37df6-ba1a-4eed-bb64-623fc8e8dfd0",
  "topic": "py39-py -- Regular expression Denial of Service vulnerability",
  "affects": [
    {
      "name": [
        "py39-py"
      ],
      "range": [
        {
          "le": "1.11.0"
        }
      ]
    }
  ],
  "description": {
    "xmlns": "http://www.w3.org/1999/xhtml",
    "text": "\n    <p>SCH227 reports:</p>\n    <blockquote cite=\"https://osv.dev/vulnerability/PYSEC-2022-42969\">\n      <p>The py library through 1.11.0 for Python allows remote attackers to conduct a ReDoS (Regular expression Denial of Service) attack via a Subversion repository with crafted info data, because the InfoSvnCommand argument is mishandled.</p>\n    </blockquote>\n      "
  },
  "references": {
    "url": [
      "https://osv.dev/vulnerability/PYSEC-2022-42969",
      "https://osv.dev/vulnerability/GHSA-w596-4wvx-j9j6"
    ],
    "cvename": [
      "CVE-2022-42969"
    ]
  },
  "dates": {
    "discovery": "2022-11-04",
    "entry": "2023-04-09"
  }
}
