{
  "vid": "c0f122e2-3897-11e3-a084-3c970e169bc2",
  "topic": "pycrypto -- PRNG reseed race condition",
  "affects": [
    {
      "name": [
        "py26-pycrypto"
      ],
      "range": [
        {
          "lt": "2.6.1"
        }
      ]
    },
    {
      "name": [
        "py27-pycrypto"
      ],
      "range": [
        {
          "lt": "2.6.1"
        }
      ]
    },
    {
      "name": [
        "py31-pycrypto"
      ],
      "range": [
        {
          "lt": "2.6.1"
        }
      ]
    },
    {
      "name": [
        "py32-pycrypto"
      ],
      "range": [
        {
          "lt": "2.6.1"
        }
      ]
    },
    {
      "name": [
        "py33-pycrypto"
      ],
      "range": [
        {
          "lt": "2.6.1"
        }
      ]
    }
  ],
  "description": {
    "xmlns": "http://www.w3.org/1999/xhtml",
    "text": "\n\t<p>Dwayne Litzenberger reports:</p>\n\t<blockquote cite=\"http://lists.dlitz.net/pipermail/pycrypto/2013q4/000702.html\">\n\t  <p>In PyCrypto before v2.6.1, the Crypto.Random pseudo-random\n\t    number generator (PRNG) exhibits a race condition that may cause\n\t    it to generate the same 'random' output in multiple processes that\n\t    are forked from each other.  Depending on the application, this\n\t    could reveal sensitive information or cryptographic keys to remote\n\t    attackers.</p>\n\t</blockquote>\n      "
  },
  "references": {
    "url": [
      "http://lists.dlitz.net/pipermail/pycrypto/2013q4/000702.html"
    ],
    "cvename": [
      "CVE-2013-1445"
    ]
  },
  "dates": {
    "discovery": "2013-10-17",
    "entry": "2013-10-19",
    "modified": "2014-04-30"
  }
}
