{
	"vid": "c2c89dea-2859-4231-8f3b-012be0d475ff",
	"topic": "py-django-photologue -- XSS vulnerability",
	"affects": [
		{
			"name": [
				"py37-django-photologue",
				"py38-django-photologue",
				"py39-django-photologue",
				"py310-django-photologue",
				"py311-django-photologue"
			],
			"range": [
				{
					"le": "3.15_1"
				}
			]
		}
	],
	"description": {
		"xmlns": "http://www.w3.org/1999/xhtml",
		"text": "\n    <p>domiee13 reports:</p>\n    <blockquote cite=\"https://osv.dev/vulnerability/GHSA-287q-jfcp-9vhv\">\n      <p>A vulnerability was found in django-photologue up to 3.15.1 and classified as problematic.</p>\n      <p>Affected by this issue is some unknown functionality of the file photologue/templates/photologue/photo_detail.html of the component Default Template Handler.</p>\n      <p>The manipulation of the argument object.caption leads to cross site scripting.</p>\n      <p>The attack may be launched remotely.</p>\n      <p>Upgrading to version 3.16 is able to address this issue.</p>\n      <p>The name of the patch is 960cb060ce5e2964e6d716ff787c72fc18a371e7.</p>\n      <p>It is recommended to apply a patch to fix this issue.</p>\n      <p>VDB-215906 is the identifier assigned to this vulnerability.</p>\n    </blockquote>\n      "
	},
	"references": {
		"url": [
			"https://osv.dev/vulnerability/GHSA-287q-jfcp-9vhv"
		],
		"cvename": [
			"CVE-2022-4526"
		]
	},
	"dates": {
		"discovery": "2022-12-15",
		"entry": "2023-08-31"
	}
}
