{
	"vid": "c7ec6375-c3cf-11eb-904f-14dae9d5a9d2",
	"topic": "PyYAML -- arbitrary code execution",
	"affects": [
		{
			"name": [
				"py36-yaml",
				"py37-yaml",
				"py38-yaml",
				"py39-yaml"
			],
			"range": [
				{
					"lt": "5.4"
				}
			]
		}
	],
	"description": {
		"xmlns": "http://www.w3.org/1999/xhtml",
		"text": "\n\t<p>A vulnerability was discovered in the PyYAML library\n\tin versions before 5.4, where it is susceptible to arbitrary\n\tcode execution when it processes untrusted YAML files\n\tthrough the full_load method or with the FullLoader loader.\n\tApplications that use the library to process untrusted\n\tinput may be vulnerable to this flaw. This flaw allows\n\tan attacker to execute arbitrary code on the system by\n\tabusing the python/object/new constructor. This flaw is\n\tdue to an incomplete fix for CVE-2020-1747.</p>\n      "
	},
	"references": {
		"url": [
			"https://github.com/yaml/pyyaml/issues/420",
			"https://access.redhat.com/security/cve/CVE-2020-14343",
			"https://bugzilla.redhat.com/show_bug.cgi?id=1860466"
		],
		"cvename": [
			"CVE-2020-14343"
		]
	},
	"dates": {
		"discovery": "2020-07-22",
		"entry": "2021-06-02"
	}
}
