{
  "vid": "d55e1b4d-eadc-11ed-9cc0-080027de9982",
  "topic": "Django -- multiple vulnerabilities",
  "affects": [
    {
      "name": [
        "py37-django32",
        "py38-django32",
        "py39-django32",
        "py310-django32",
        "py311-django32"
      ],
      "range": [
        {
          "lt": "3.2.19"
        }
      ]
    },
    {
      "name": [
        "py38-django41",
        "py39-django41",
        "py310-django41",
        "py311-django41"
      ],
      "range": [
        {
          "lt": "4.1.9"
        }
      ]
    },
    {
      "name": [
        "py38-django42",
        "py39-django42",
        "py310-django42",
        "py311-django42"
      ],
      "range": [
        {
          "lt": "4.2.1"
        }
      ]
    }
  ],
  "description": {
    "xmlns": "http://www.w3.org/1999/xhtml",
    "text": "\n\t<p>Django reports:</p>\n\t<blockquote cite=\"https://www.djangoproject.com/weblog/2023/may/03/security-releases/\">\n\t  <p>CVE-2023-31047: Potential bypass of validation when uploading multiple\n\t    files using one form field.</p>\n\t</blockquote>\n      "
  },
  "references": {
    "url": [
      "https://www.djangoproject.com/weblog/2023/may/03/security-releases/"
    ],
    "cvename": [
      "CVE-2023-31047"
    ]
  },
  "dates": {
    "discovery": "2023-05-01",
    "entry": "2023-05-05"
  }
}
