{
  "vid": "fb67567a-5d95-11eb-a955-08002728f74c",
  "topic": "pysaml2 -- multiple vulnerabilities",
  "affects": [
    {
      "name": [
        "py36-pysaml2",
        "py37-pysaml2",
        "py38-pysaml2",
        "py39-pysaml2"
      ],
      "range": [
        {
          "lt": "6.5.0"
        }
      ]
    }
  ],
  "description": {
    "xmlns": "http://www.w3.org/1999/xhtml",
    "text": "\n\t<p>pysaml2 Releases:</p>\n\t<blockquote cite=\"https://github.com/IdentityPython/pysaml2/releases\">\n\t  <p>Fix processing of invalid SAML XML documents - CVE-2021-21238</p>\n\t  <p>Fix unspecified xmlsec1 key-type preference - CVE-2021-21239</p>\n\t</blockquote>\n      "
  },
  "references": {
    "url": [
      "https://github.com/IdentityPython/pysaml2/releases",
      "https://github.com/IdentityPython/pysaml2/security/advisories/GHSA-f4g9-h89h-jgv9",
      "https://github.com/IdentityPython/pysaml2/security/advisories/GHSA-5p3x-r448-pc62"
    ],
    "cvename": [
      "CVE-2021-21238",
      "CVE-2021-21239"
    ]
  },
  "dates": {
    "discovery": "2021-01-20",
    "entry": "2021-01-26"
  }
}
